declare module '*.png'
declare module '*.jpg'

declare module 'react-native-modal-dropdown'
declare module 'react-native-languages'
declare module 'react-native-restart-android'
declare module 'react-native-mail'
declare module 'svgs'
declare module 'react-native-restart-android'
declare module 'react-native-platform-touchable'
declare module 'web3-utils'
declare module 'redux-persist/lib/stateReconciler/autoMergeLevel2'
