#!/bin/bash
set -x

# authorize a new signer

CELO_VALIDATOR_RG_ADDRESS=FIXME
SIGNER_TO_AUTHORIZE=FIXME
SIGNER_PROOF_OF_POSSESSION=FIXME
BLS_PUBLIC_KEY=FIXME
BLS_PROOF_OF_POSSESSION=FIXME
LEDGER_INDEX=0

# DO NOT RUN THE FOLLOWING UNTIL THE NEW SIGNER IS READY TO ROCK AND ROLL.
# NEW SIGNER WILL TAKE OVER FOR OLD SIGNER AT BEGINNING OF NEW EPOCH

# From a node with access to the beneficiary key of VALIDATOR_ACCOUNT_ADDRESS
npx celocli releasegold:authorize --contract $CELO_VALIDATOR_RG_ADDRESS --role validator \
    --signer $SIGNER_TO_AUTHORIZE --signature 0x$SIGNER_PROOF_OF_POSSESSION --blsKey $BLS_PUBLIC_KEY --blsPop $BLS_PROOF_OF_POSSESSION \
    --useLedger --ledgerCustomAddresses=$LEDGER_INDEX

