export default {
  getApiLevel: jest.fn(),
  getApiLevelSync: jest.fn(),
  getApplicationName: jest.fn(),
  getBrand: jest.fn(),
  getBuildNumber: jest.fn(),
  getBundleId: jest.fn(() => 'org.celo.mobile.debug'),
  getDeviceCountry: jest.fn(),
  getDeviceId: jest.fn(),
  getDeviceLocale: jest.fn(),
  getDeviceName: jest.fn(),
  getFirstInstallTime: () => 1,
  getFontScale: () => 16,
  getInstallReferrer: () => null,
  getInstanceID: jest.fn(),
  getLastUpdateTime: () => 1,
  getManufacturer: jest.fn(),
  getModel: jest.fn(),
  getReadableVersion: jest.fn(),
  getSerialNumber: jest.fn(),
  getSystemName: jest.fn(),
  getSystemVersion: jest.fn(),
  getTimezone: jest.fn(),
  getUniqueID: jest.fn(),
  getUserAgent: jest.fn(),
  getVersion: jest.fn(() => 'appVersion'),
  hasNotch: () => true,
  is24Hour: () => false,
  isEmulator: () => true,
  isPinOrFingerprintSet: jest.fn(),
  isTablet: () => false,
}
