{
 "title": "Celo Governance",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "label": "quantile", "query": "label_values(quantile)" },
   {
    "name": "network",
    "label": "network",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "component", "label": "component", "query": "label_values(component)" }
  ]
 },
 "panels": [
  {
   "title": "Chain Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chain_head_block{kubernetes_namespace=\"jctest2\",component=\"validators\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Chain Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chain_head_block{kubernetes_namespace=\"jctest2\",component=\"proxy\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Blocks Signed ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "5*rate(consensus_istanbul_blocks_signedbyus{kubernetes_namespace=\"$network\",component=\"$component\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Blocks Missed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "5*rate(consensus_istanbul_blocks_missedbyus{kubernetes_namespace=\"$network\",component=\"$component\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Desired Round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_istanbul_core_desiredround{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Validators elected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "5*rate(consensus_istanbul_blocks_elected{kubernetes_namespace=\"$network\",component=\"validators\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_memory_used{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Load avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(system_cpu_sysload{kubernetes_namespace=\"$network\",component=\"$component\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}|system_cpu_sysload"
    }
   ]
  },
  {
   "title": "Chain inserts per blocktime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "5*rate(chain_inserts_count{kubernetes_namespace=\"$network\",component=\"$component\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}