{
 "title": "Official Geth Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   {
    "name": "network",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "component", "label": "component", "query": "label_values(component)" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "system {{kubernetes_pod_name}}"
    },
    {
     "expr": "system_cpu_syswait{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "iowait {{kubernetes_pod_name}}"
    },
    {
     "expr": "system_cpu_procload{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "geth {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "alloc {{kubernetes_pod_name}}"
    },
    {
     "expr": "system_memory_used{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "used {{kubernetes_pod_name}}"
    },
    {
     "expr": "system_memory_held{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "held {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "read {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(system_disk_writebytes{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "write {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "ingress {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(p2p_egress{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "egress {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "peers {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(p2p_dials{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "dials {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(p2p_serves{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "serves {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "header {{kubernetes_pod_name}}"
    },
    {
     "expr": "chain_head_receipt{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "receipt {{kubernetes_pod_name}}"
    },
    {
     "expr": "chain_head_block{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "block {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Latest header",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(chain_head_header{kubernetes_namespace=\"$network\"})"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(txpool_queued{kubernetes_namespace=\"$network\",component=\"$component\"})"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "executable {{kubernetes_pod_name}}"
    },
    {
     "expr": "txpool_queued{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "gapped {{kubernetes_pod_name}}"
    },
    {
     "expr": "txpool_local{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "local {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(chain_head_receipt{kubernetes_namespace=\"$network\"})"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(txpool_local{kubernetes_namespace=\"$network\"})"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(chain_head_block{kubernetes_namespace=\"$network\"})"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(txpool_pending{kubernetes_namespace=\"$network\"})"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "execution {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "validation {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "commit {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "account read {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "account update {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "account hashe {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "account commit {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "storage read {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "storage hashe {{kubernetes_pod_name}} (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\",kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "storage commit {{kubernetes_pod_name}} (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "valid {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_invalid{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "invalid {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_underpriced{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "underpriced {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_pending_discard{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "executable discard {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_pending_replace{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "executable replace {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "executable ratelimit {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_pending_nofunds{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "executable nofunds {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_queued_discard{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "gapped discard {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_queued_replace{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "gapped replace {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "gapped ratelimit {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(txpool_queued_nofunds{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "gapped nofunds {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "leveldb read {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "leveldb write {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "ancient read {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "ancient write {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "leveldb read {{kubernetes_pod_name}}"
    },
    {
     "expr": "eth_db_chaindata_disk_write{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "leveldb write {{kubernetes_pod_name}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "ancient read {{kubernetes_pod_name}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "ancient write {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "leveldb {{kubernetes_pod_name}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{kubernetes_namespace=\"$network\",component=\"$component\"}",
     "legendFormat": "ancient {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "hit {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(trie_memcache_clean_write{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "miss {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size{kubernetes_namespace=\"$network\",component=\"$component\"}[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}