export enum Stacks {
  AppStack = 'AppStack',
  NuxStack = 'NuxStack',
}

export enum Screens {
  Account = 'Account',
  Backup = 'Backup',
  Debug = 'Debug',
  DollarEducation = 'DollarEducation',
  EditProfile = 'EditProfile',
  ErrorScreen = 'ErrorScreen',
  UpgradeScreen = 'UpgradeScreen',
  ExchangeHomeScreen = 'ExchangeHomeScreen',
  ExchangeReview = 'ExchangeReview',
  ExchangeStack = 'ExchangeStack',
  ExchangeTradeScreen = 'ExchangeTradeScreen',
  FeeEducation = 'FeeEducation',
  GoldEducation = 'GoldEducation',
  ImportWallet = 'ImportWallet',
  Invite = 'Invite',
  InviteReview = 'InviteReview',
  ImportContacts = 'ImportContacts',
  JoinCelo = 'JoinCelo',
  EnterInviteCode = 'EnterInviteCode',
  Analytics = 'Analytics',
  Language = 'Language',
  Licenses = 'Licenses',
  PaymentRequestListScreen = 'PaymentRequestListScreen',
  PhotosEducation = 'PhotosEducation',
  PhotosNUX = 'PhotosNUX',
  Pincode = 'Pincode',
  PincodeConfirmation = 'PincodeConfirmation',
  Profile = 'Profile',
  QRCode = 'QRCode',
  QRScanner = 'QRScanner',
  ReclaimPaymentConfirmationScreen = 'ReclaimPaymentConfirmationScreen',
  RequestConfirmation = 'RequestConfirmation',
  Send = 'Send',
  SendAmount = 'SendAmount',
  SendConfirmation = 'SendConfirmation',
  SendStack = 'SendStack',
  SetClock = 'SetClock',
  Settings = 'Settings',
  Sync = 'Sync',
  TransactionReview = 'TransactionReview',
  VerifyEducation = 'VerifyEducation',
  VerifyInput = 'VerifyInput',
  VerifyVerified = 'VerifyVerified',
  VerifyVerifying = 'VerifyVerifying',
  WalletHome = 'WalletHome',
}
