declare module '*.json' {
  const value: any
  export default value
}

declare module '*.png'
declare module '*.jpg'

declare module 'react-native-tcp'
declare module 'react-native-send-intent'
declare module 'sleep-promise'
declare module 'react-native-progress/Bar'
declare module 'dot-prop-immutable'
declare module 'react-native-clock-sync'
declare module 'react-native-crypto'
declare module 'react-native-bip39'
declare module 'react-native-flag-secure-android'
declare module 'react-native-google-safetynet'
declare module 'svgs'
declare module 'react-native-languages'
declare module 'react-native-version-check'
declare module 'react-native-randombytes'
declare module 'react-native-restart-android'
declare module 'react-native-mail'
declare module 'react-native-platform-touchable'
declare module 'react-native-shake'
declare module 'numeral'
declare module 'redux-persist/lib/stateReconciler/autoMergeLevel2'
declare module '@celo/react-native-sms-retriever'
declare module 'futoin-hkdf'
declare module 'react-native-share'
declare module 'react-native-qrcode-svg'
declare module 'eth-lib'
declare module '@ungap/url-search-params'
declare module 'react-native-install-referrer'
declare module 'react-native-secure-randombytes'
