/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class BlockchainParameters extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getMinimumClientVersion(): TransactionObject<{
      major: string
      minor: string
      patch: string
      0: string
      1: string
      2: string
    }>

    renounceOwnership(): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(
      major: number | string,
      minor: number | string,
      patch: number | string,
      _gasForNonGoldCurrencies: number | string,
      gasLimit: number | string
    ): TransactionObject<void>

    setMinimumClientVersion(
      major: number | string,
      minor: number | string,
      patch: number | string
    ): TransactionObject<void>

    setBlockGasLimit(gasLimit: number | string): TransactionObject<void>

    setIntrinsicGasForAlternativeFeeCurrency(gas: number | string): TransactionObject<void>

    initialized(): TransactionObject<boolean>
    blockGasLimit(): TransactionObject<string>
    intrinsicGasForAlternativeFeeCurrency(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    MinimumClientVersionSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    IntrinsicGasForAlternativeFeeCurrencySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    BlockGasLimitSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): BlockchainParameters
}
