/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class EpochRewardsTest extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    validatorSignerAddressFromCurrentSet(index: number | string): TransactionObject<string>

    getTargetVotingYieldParameters(): TransactionObject<{
      0: string
      1: string
      2: string
    }>

    checkProofOfPossession(
      sender: string,
      blsKey: (string | number[])[],
      blsPop: (string | number[])[]
    ): TransactionObject<boolean>

    getEpochNumberOfBlock(blockNumber: number | string): TransactionObject<string>

    getVerifiedSealBitmapFromHeader(header: (string | number[])[]): TransactionObject<string>

    validatorSignerAddressFromSet(
      index: number | string,
      blockNumber: number | string
    ): TransactionObject<string>

    getRewardsMultiplierParameters(): TransactionObject<{
      0: string
      1: string
      2: string
    }>

    calculateTargetEpochRewards(): TransactionObject<{
      0: string
      1: string
      2: string
      3: string
    }>

    hashHeader(header: (string | number[])[]): TransactionObject<string>

    getBlockNumberFromHeader(header: (string | number[])[]): TransactionObject<string>

    numberValidatorsInSet(blockNumber: number | string): TransactionObject<string>

    minQuorumSize(blockNumber: number | string): TransactionObject<string>

    fractionMulExp(
      aNumerator: number | string,
      aDenominator: number | string,
      bNumerator: number | string,
      bDenominator: number | string,
      exponent: number | string,
      _decimals: number | string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getParentSealBitmap(blockNumber: number | string): TransactionObject<string>

    setCarbonOffsettingFund(partner: string, value: number | string): TransactionObject<boolean>

    setTargetVotingYieldParameters(
      max: number | string,
      adjustmentFactor: number | string
    ): TransactionObject<boolean>

    renounceOwnership(): TransactionObject<void>

    initialize(
      registryAddress: string,
      targetVotingYieldInitial: number | string,
      targetVotingYieldMax: number | string,
      targetVotingYieldAdjustmentFactor: number | string,
      rewardsMultiplierMax: number | string,
      rewardsMultiplierUnderspendAdjustmentFactor: number | string,
      rewardsMultiplierOverspendAdjustmentFactor: number | string,
      _targetVotingGoldFraction: number | string,
      _targetValidatorEpochPayment: number | string,
      _communityRewardFraction: number | string,
      _carbonOffsettingPartner: string,
      _carbonOffsettingFraction: number | string
    ): TransactionObject<void>

    setRewardsMultiplierParameters(
      max: number | string,
      underspendAdjustmentFactor: number | string,
      overspendAdjustmentFactor: number | string
    ): TransactionObject<boolean>

    setTargetVotingGoldFraction(value: number | string): TransactionObject<boolean>

    setTargetValidatorEpochPayment(value: number | string): TransactionObject<boolean>

    setRegistry(registryAddress: string): TransactionObject<void>

    setCommunityRewardFraction(value: number | string): TransactionObject<boolean>

    setTargetVotingYield(targetVotingYield: number | string): TransactionObject<boolean>

    transferOwnership(newOwner: string): TransactionObject<void>

    updateTargetVotingYield(): TransactionObject<void>

    setNumberValidatorsInCurrentSet(value: number | string): TransactionObject<void>

    initialized(): TransactionObject<boolean>
    carbonOffsettingPartner(): TransactionObject<string>
    getTargetVoterRewards(): TransactionObject<string>
    getTargetTotalEpochPaymentsInGold(): TransactionObject<string>
    getTargetGoldTotalSupply(): TransactionObject<string>
    minQuorumSizeInCurrentSet(): TransactionObject<string>
    startTime(): TransactionObject<string>
    registry(): TransactionObject<string>
    getCarbonOffsettingFraction(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    getCommunityRewardFraction(): TransactionObject<string>
    getEpochNumber(): TransactionObject<string>
    isReserveLow(): TransactionObject<boolean>
    getVotingGoldFraction(): TransactionObject<string>
    getTargetVotingGoldFraction(): TransactionObject<string>
    getEpochSize(): TransactionObject<string>
    targetValidatorEpochPayment(): TransactionObject<string>
    getRewardsMultiplier(): TransactionObject<string>
    numberValidatorsInCurrentSet(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    TargetVotingGoldFractionSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    CommunityRewardFractionSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    CarbonOffsettingFundSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TargetValidatorEpochPaymentSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TargetVotingYieldParametersSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TargetVotingYieldSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RewardsMultiplierParametersSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TargetVotingYieldUpdated(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RegistrySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): EpochRewardsTest
}
