/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class FixidityTest extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    newFixed(a: number | string): TransactionObject<string>

    newFixedFraction(a: number | string, b: number | string): TransactionObject<string>

    add(a: number | string, b: number | string): TransactionObject<string>

    subtract(a: number | string, b: number | string): TransactionObject<string>

    multiply(a: number | string, b: number | string): TransactionObject<string>

    reciprocal(a: number | string): TransactionObject<string>

    divide(a: number | string, b: number | string): TransactionObject<string>

    gt(a: number | string, b: number | string): TransactionObject<boolean>

    gte(a: number | string, b: number | string): TransactionObject<boolean>

    lt(a: number | string, b: number | string): TransactionObject<boolean>

    lte(a: number | string, b: number | string): TransactionObject<boolean>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): FixidityTest
}
