/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class GasPriceMinimum extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getGasPriceMinimum(tokenAddress: string): TransactionObject<string>

    getUpdatedGasPriceMinimum(
      blockGasTotal: number | string,
      blockGasLimit: number | string
    ): TransactionObject<string>

    renounceOwnership(): TransactionObject<void>

    setRegistry(registryAddress: string): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(
      _registryAddress: string,
      _gasPriceMinimumFloor: number | string,
      _targetDensity: number | string,
      _adjustmentSpeed: number | string
    ): TransactionObject<void>

    setAdjustmentSpeed(_adjustmentSpeed: number | string): TransactionObject<void>

    setTargetDensity(_targetDensity: number | string): TransactionObject<void>

    setGasPriceMinimumFloor(_gasPriceMinimumFloor: number | string): TransactionObject<void>

    updateGasPriceMinimum(
      blockGasTotal: number | string,
      blockGasLimit: number | string
    ): TransactionObject<string>

    initialized(): TransactionObject<boolean>
    gasPriceMinimum(): TransactionObject<string>
    targetDensity(): TransactionObject<string>
    registry(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    adjustmentSpeed(): TransactionObject<string>
    gasPriceMinimumFloor(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    TargetDensitySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    GasPriceMinimumFloorSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AdjustmentSpeedSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    GasPriceMinimumUpdated(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RegistrySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): GasPriceMinimum
}
