/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class Governance extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    stageDurations(): TransactionObject<{
      approval: string
      referendum: string
      execution: string
      0: string
      1: string
      2: string
    }>

    validatorSignerAddressFromCurrentSet(index: number | string): TransactionObject<string>

    checkProofOfPossession(
      sender: string,
      blsKey: (string | number[])[],
      blsPop: (string | number[])[]
    ): TransactionObject<boolean>

    getEpochNumberOfBlock(blockNumber: number | string): TransactionObject<string>

    hotfixes(
      arg0: string | number[]
    ): TransactionObject<{
      executed: boolean
      approved: boolean
      preparedEpoch: string
      0: boolean
      1: boolean
      2: string
    }>

    getVerifiedSealBitmapFromHeader(header: (string | number[])[]): TransactionObject<string>

    validatorSignerAddressFromSet(
      index: number | string,
      blockNumber: number | string
    ): TransactionObject<string>

    refundedDeposits(arg0: string): TransactionObject<string>

    hashHeader(header: (string | number[])[]): TransactionObject<string>

    getBlockNumberFromHeader(header: (string | number[])[]): TransactionObject<string>

    numberValidatorsInSet(blockNumber: number | string): TransactionObject<string>

    emptyIndices(arg0: number | string): TransactionObject<string>

    dequeued(arg0: number | string): TransactionObject<string>

    minQuorumSize(blockNumber: number | string): TransactionObject<string>

    fractionMulExp(
      aNumerator: number | string,
      aDenominator: number | string,
      bNumerator: number | string,
      bDenominator: number | string,
      exponent: number | string,
      _decimals: number | string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getParentSealBitmap(blockNumber: number | string): TransactionObject<string>

    getProposalStage(proposalId: number | string): TransactionObject<string>

    isHotfixWhitelistedBy(hash: string | number[], whitelister: string): TransactionObject<boolean>

    isVoting(account: string): TransactionObject<boolean>

    getParticipationParameters(): TransactionObject<{
      0: string
      1: string
      2: string
      3: string
    }>

    proposalExists(proposalId: number | string): TransactionObject<boolean>

    getProposal(
      proposalId: number | string
    ): TransactionObject<{
      0: string
      1: string
      2: string
      3: string
      4: string
    }>

    getProposalTransaction(
      proposalId: number | string,
      index: number | string
    ): TransactionObject<{
      0: string
      1: string
      2: string[]
    }>

    isApproved(proposalId: number | string): TransactionObject<boolean>

    getVoteTotals(
      proposalId: number | string
    ): TransactionObject<{
      0: string
      1: string
      2: string
    }>

    getVoteRecord(
      account: string,
      index: number | string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getUpvotes(proposalId: number | string): TransactionObject<string>

    getQueue(): TransactionObject<{
      0: string[]
      1: string[]
    }>

    getUpvoteRecord(
      account: string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getMostRecentReferendumProposal(account: string): TransactionObject<string>

    hotfixWhitelistValidatorTally(hash: string | number[]): TransactionObject<string>

    isHotfixPassing(hash: string | number[]): TransactionObject<boolean>

    getHotfixRecord(
      hash: string | number[]
    ): TransactionObject<{
      0: boolean
      1: boolean
      2: string
    }>

    isQueued(proposalId: number | string): TransactionObject<boolean>

    isProposalPassing(proposalId: number | string): TransactionObject<boolean>

    isDequeuedProposal(
      proposalId: number | string,
      index: number | string
    ): TransactionObject<boolean>

    isDequeuedProposalExpired(proposalId: number | string): TransactionObject<boolean>

    isQueuedProposalExpired(proposalId: number | string): TransactionObject<boolean>

    getConstitution(destination: string, functionId: string | number[]): TransactionObject<string>

    renounceOwnership(): TransactionObject<void>

    setRegistry(registryAddress: string): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(
      registryAddress: string,
      _approver: string,
      _concurrentProposals: number | string,
      _minDeposit: number | string,
      _queueExpiry: number | string,
      _dequeueFrequency: number | string,
      approvalStageDuration: number | string,
      referendumStageDuration: number | string,
      executionStageDuration: number | string,
      participationBaseline: number | string,
      participationFloor: number | string,
      baselineUpdateFactor: number | string,
      baselineQuorumFactor: number | string
    ): TransactionObject<void>

    setApprover(_approver: string): TransactionObject<void>

    setConcurrentProposals(_concurrentProposals: number | string): TransactionObject<void>

    setMinDeposit(_minDeposit: number | string): TransactionObject<void>

    setQueueExpiry(_queueExpiry: number | string): TransactionObject<void>

    setDequeueFrequency(_dequeueFrequency: number | string): TransactionObject<void>

    setApprovalStageDuration(approvalStageDuration: number | string): TransactionObject<void>

    setReferendumStageDuration(referendumStageDuration: number | string): TransactionObject<void>

    setExecutionStageDuration(executionStageDuration: number | string): TransactionObject<void>

    setParticipationBaseline(participationBaseline: number | string): TransactionObject<void>

    setParticipationFloor(participationFloor: number | string): TransactionObject<void>

    setBaselineUpdateFactor(baselineUpdateFactor: number | string): TransactionObject<void>

    setBaselineQuorumFactor(baselineQuorumFactor: number | string): TransactionObject<void>

    setConstitution(
      destination: string,
      functionId: string | number[],
      threshold: number | string
    ): TransactionObject<void>

    propose(
      values: (number | string)[],
      destinations: string[],
      data: (string | number[])[],
      dataLengths: (number | string)[],
      descriptionUrl: string
    ): TransactionObject<string>

    upvote(
      proposalId: number | string,
      lesser: number | string,
      greater: number | string
    ): TransactionObject<boolean>

    revokeUpvote(lesser: number | string, greater: number | string): TransactionObject<boolean>

    approve(proposalId: number | string, index: number | string): TransactionObject<boolean>

    vote(
      proposalId: number | string,
      index: number | string,
      value: number | string
    ): TransactionObject<boolean>

    execute(proposalId: number | string, index: number | string): TransactionObject<boolean>

    approveHotfix(hash: string | number[]): TransactionObject<void>

    whitelistHotfix(hash: string | number[]): TransactionObject<void>

    prepareHotfix(hash: string | number[]): TransactionObject<void>

    executeHotfix(
      values: (number | string)[],
      destinations: string[],
      data: (string | number[])[],
      dataLengths: (number | string)[],
      salt: string | number[]
    ): TransactionObject<void>

    withdraw(): TransactionObject<boolean>

    dequeueProposalsIfReady(): TransactionObject<void>

    concurrentProposals(): TransactionObject<string>
    approver(): TransactionObject<string>
    initialized(): TransactionObject<boolean>
    minDeposit(): TransactionObject<string>
    minQuorumSizeInCurrentSet(): TransactionObject<string>
    dequeueFrequency(): TransactionObject<string>
    registry(): TransactionObject<string>
    numberValidatorsInCurrentSet(): TransactionObject<string>
    owner(): TransactionObject<string>
    queueExpiry(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    getEpochNumber(): TransactionObject<string>
    lastDequeue(): TransactionObject<string>
    proposalCount(): TransactionObject<string>
    getEpochSize(): TransactionObject<string>
    getApprovalStageDuration(): TransactionObject<string>
    getReferendumStageDuration(): TransactionObject<string>
    getExecutionStageDuration(): TransactionObject<string>
    getQueueLength(): TransactionObject<string>
    getDequeue(): TransactionObject<string[]>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    ApproverSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ConcurrentProposalsSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    MinDepositSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    QueueExpirySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    DequeueFrequencySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ApprovalStageDurationSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ReferendumStageDurationSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ExecutionStageDurationSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ConstitutionSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalQueued(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalUpvoted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalUpvoteRevoked(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalDequeued(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalApproved(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalVoted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalExecuted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ProposalExpired(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ParticipationBaselineUpdated(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ParticipationFloorSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ParticipationBaselineUpdateFactorSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ParticipationBaselineQuorumFactorSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    HotfixWhitelisted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    HotfixApproved(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    HotfixPrepared(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    HotfixExecuted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RegistrySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): Governance
}
