/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IAttestations extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getUnselectedRequest(
      arg0: string | number[],
      arg1: string
    ): TransactionObject<{
      0: string
      1: string
      2: string
    }>

    getAttestationRequestFee(arg0: string): TransactionObject<string>

    lookupAccountsForIdentifier(arg0: string | number[]): TransactionObject<string[]>

    getAttestationStats(
      arg0: string | number[],
      arg1: string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getAttestationState(
      arg0: string | number[],
      arg1: string,
      arg2: string
    ): TransactionObject<{
      0: string
      1: string
      2: string
    }>

    getCompletableAttestations(
      arg0: string | number[],
      arg1: string
    ): TransactionObject<{
      0: string[]
      1: string[]
      2: string[]
      3: string[]
    }>

    setAttestationRequestFee(arg0: string, arg1: number | string): TransactionObject<void>

    request(arg0: string | number[], arg1: number | string, arg2: string): TransactionObject<void>

    selectIssuers(arg0: string | number[]): TransactionObject<void>

    complete(
      arg0: string | number[],
      arg1: number | string,
      arg2: string | number[],
      arg3: string | number[]
    ): TransactionObject<void>

    revoke(arg0: string | number[], arg1: number | string): TransactionObject<void>

    withdraw(arg0: string): TransactionObject<void>

    setAttestationExpiryBlocks(arg0: number | string): TransactionObject<void>

    getMaxAttestations(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IAttestations
}
