/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class ILockedGold extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getAccountTotalLockedGold(arg0: string): TransactionObject<string>

    getPendingWithdrawals(
      arg0: string
    ): TransactionObject<{
      0: string[]
      1: string[]
    }>

    getTotalPendingWithdrawals(arg0: string): TransactionObject<string>

    isSlasher(arg0: string): TransactionObject<boolean>

    incrementNonvotingAccountBalance(arg0: string, arg1: number | string): TransactionObject<void>

    decrementNonvotingAccountBalance(arg0: string, arg1: number | string): TransactionObject<void>

    lock(): TransactionObject<void>

    unlock(arg0: number | string): TransactionObject<void>

    relock(arg0: number | string, arg1: number | string): TransactionObject<void>

    withdraw(arg0: number | string): TransactionObject<void>

    slash(
      account: string,
      penalty: number | string,
      reporter: string,
      reward: number | string,
      lessers: string[],
      greaters: string[],
      indices: (number | string)[]
    ): TransactionObject<void>

    getTotalLockedGold(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): ILockedGold
}
