/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IReserve extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    setTobinTaxStalenessThreshold(arg0: number | string): TransactionObject<void>

    addToken(arg0: string): TransactionObject<boolean>

    removeToken(arg0: string, arg1: number | string): TransactionObject<boolean>

    transferGold(arg0: string, arg1: number | string): TransactionObject<boolean>

    transferExchangeGold(arg0: string, arg1: number | string): TransactionObject<boolean>

    getOrComputeTobinTax(): TransactionObject<{
      0: string
      1: string
    }>

    getReserveGoldBalance(): TransactionObject<string>
    getUnfrozenReserveGoldBalance(): TransactionObject<string>
    getTokens(): TransactionObject<string[]>
    getReserveRatio(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IReserve
}
