/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IStableToken extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    valueToUnits(arg0: number | string): TransactionObject<string>

    unitsToValue(arg0: number | string): TransactionObject<string>

    getInflationParameters(): TransactionObject<{
      0: string
      1: string
      2: string
      3: string
    }>

    balanceOf(arg0: string): TransactionObject<string>

    mint(arg0: string, arg1: number | string): TransactionObject<boolean>

    burn(arg0: number | string): TransactionObject<boolean>

    setInflationParameters(arg0: number | string, arg1: number | string): TransactionObject<void>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IStableToken
}
