/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IValidators extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getAccountLockedGoldRequirement(arg0: string): TransactionObject<string>

    meetsAccountLockedGoldRequirements(arg0: string): TransactionObject<boolean>

    getGroupNumMembers(arg0: string): TransactionObject<string>

    getGroupsNumMembers(arg0: string[]): TransactionObject<string[]>

    getTopGroupValidators(arg0: string, arg1: number | string): TransactionObject<string[]>

    isValidator(arg0: string): TransactionObject<boolean>

    isValidatorGroup(arg0: string): TransactionObject<boolean>

    calculateGroupEpochScore(uptimes: (number | string)[]): TransactionObject<string>

    groupMembershipInEpoch(
      account: string,
      epochNumber: number | string,
      index: number | string
    ): TransactionObject<string>

    getValidatorGroupSlashingMultiplier(arg0: string): TransactionObject<string>

    updateEcdsaPublicKey(
      arg0: string,
      arg1: string,
      arg2: (string | number[])[]
    ): TransactionObject<boolean>

    updatePublicKeys(
      arg0: string,
      arg1: string,
      arg2: (string | number[])[],
      arg3: (string | number[])[],
      arg4: (string | number[])[]
    ): TransactionObject<boolean>

    halveSlashingMultiplier(group: string): TransactionObject<void>

    forceDeaffiliateIfValidator(validator: string): TransactionObject<void>

    affiliate(group: string): TransactionObject<boolean>

    getNumRegisteredValidators(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IValidators
}
