/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class MockElection extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    electedValidators(arg0: number | string): TransactionObject<string>

    isEligible(arg0: string): TransactionObject<boolean>

    isIneligible(arg0: string): TransactionObject<boolean>

    getTotalVotesByAccount(arg0: string): TransactionObject<string>

    markGroupIneligible(account: string): TransactionObject<void>

    markGroupEligible(account: string, arg1: string, arg2: string): TransactionObject<void>

    setActiveVotes(value: number | string): TransactionObject<void>

    setTotalVotes(value: number | string): TransactionObject<void>

    setElectedValidators(_electedValidators: string[]): TransactionObject<void>

    vote(
      arg0: string,
      arg1: number | string,
      arg2: string,
      arg3: string
    ): TransactionObject<boolean>

    activate(arg0: string): TransactionObject<boolean>

    revokeAllActive(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: number | string
    ): TransactionObject<boolean>

    revokeActive(
      arg0: string,
      arg1: number | string,
      arg2: string,
      arg3: string,
      arg4: number | string
    ): TransactionObject<boolean>

    revokePending(
      arg0: string,
      arg1: number | string,
      arg2: string,
      arg3: string,
      arg4: number | string
    ): TransactionObject<boolean>

    forceDecrementVotes(
      arg0: string,
      value: number | string,
      arg2: string[],
      arg3: string[],
      arg4: (number | string)[]
    ): TransactionObject<string>

    getTotalVotes(): TransactionObject<string>
    getActiveVotes(): TransactionObject<string>
    electValidatorSigners(): TransactionObject<string[]>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): MockElection
}
