/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class Reserve extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    assetAllocationSymbols(arg0: number | string): TransactionObject<string>

    isToken(arg0: string): TransactionObject<boolean>

    tobinTaxCache(): TransactionObject<{
      numerator: string
      timestamp: string
      0: string
      1: string
    }>

    otherReserveAddresses(arg0: number | string): TransactionObject<string>

    isOtherReserveAddress(arg0: string): TransactionObject<boolean>

    isSpender(arg0: string): TransactionObject<boolean>

    assetAllocationWeights(arg0: string | number[]): TransactionObject<string>

    renounceOwnership(): TransactionObject<void>

    setRegistry(registryAddress: string): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(
      registryAddress: string,
      _tobinTaxStalenessThreshold: number | string,
      _spendingRatio: number | string,
      _frozenGold: number | string,
      _frozenDays: number | string,
      _assetAllocationSymbols: (string | number[])[],
      _assetAllocationWeights: (number | string)[]
    ): TransactionObject<void>

    setTobinTaxStalenessThreshold(value: number | string): TransactionObject<void>

    setDailySpendingRatio(ratio: number | string): TransactionObject<void>

    setFrozenGold(frozenGold: number | string, frozenDays: number | string): TransactionObject<void>

    setAssetAllocations(
      symbols: (string | number[])[],
      weights: (number | string)[]
    ): TransactionObject<void>

    addToken(token: string): TransactionObject<boolean>

    removeToken(token: string, index: number | string): TransactionObject<boolean>

    addOtherReserveAddress(reserveAddress: string): TransactionObject<boolean>

    removeOtherReserveAddress(
      reserveAddress: string,
      index: number | string
    ): TransactionObject<boolean>

    addSpender(spender: string): TransactionObject<void>

    removeSpender(spender: string): TransactionObject<void>

    transferGold(to: string, value: number | string): TransactionObject<boolean>

    transferExchangeGold(to: string, value: number | string): TransactionObject<boolean>

    getOrComputeTobinTax(): TransactionObject<{
      0: string
      1: string
    }>

    frozenReserveGoldStartBalance(): TransactionObject<string>
    initialized(): TransactionObject<boolean>
    spendingLimit(): TransactionObject<string>
    TOBIN_TAX_NUMERATOR(): TransactionObject<string>
    frozenReserveGoldDays(): TransactionObject<string>
    registry(): TransactionObject<string>
    frozenReserveGoldStartDay(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    tobinTaxStalenessThreshold(): TransactionObject<string>
    lastSpendingDay(): TransactionObject<string>
    getDailySpendingRatio(): TransactionObject<string>
    getTokens(): TransactionObject<string[]>
    getOtherReserveAddresses(): TransactionObject<string[]>
    getAssetAllocationSymbols(): TransactionObject<string[]>
    getAssetAllocationWeights(): TransactionObject<string[]>
    getUnfrozenBalance(): TransactionObject<string>
    getReserveGoldBalance(): TransactionObject<string>
    getOtherReserveAddressesGoldBalance(): TransactionObject<string>
    getUnfrozenReserveGoldBalance(): TransactionObject<string>
    getFrozenReserveGoldBalance(): TransactionObject<string>
    getReserveRatio(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    TobinTaxStalenessThresholdSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    DailySpendingRatioSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TokenAdded(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    TokenRemoved(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    SpenderAdded(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    SpenderRemoved(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OtherReserveAddressAdded(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OtherReserveAddressRemoved(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AssetAllocationSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    ReserveGoldTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RegistrySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): Reserve
}
