
// Objective-C API for talking to the following Go packages
//
//	github.com/ethereum/go-ethereum/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Geth_FRAMEWORK_H__
#define __Geth_FRAMEWORK_H__

#include "Geth.objc.h"
#include "universe.objc.h"

#endif
