export const APP_NAME = 'Celo Wallet'
export const CELO_FAUCET_LINK = 'https://celo.org/developers/wallet'
export const CELO_TERMS_LINK = 'https://celo.org/terms'
export const TOS_LINK = 'https://celo.org/user-agreement'
export const FAQ_LINK = 'https://celo.org/faq'
export const FORUM_LINK = 'https://forum.celo.org/c/support'
export const CELO_SUPPORT_EMAIL_ADDRESS = 'support@celo.org'
