export enum Category {
  'Accept' = 'Accept',
  'Acquire' = 'Acquire',
  'Build' = 'Build',
  'Community' = 'Community',
  'Earn' = 'Earn',
  'Educate' = 'Educate',
  'Give' = 'Give',
  'Grow' = 'Grow',
  'Lend' = 'Lend',
  'Pay' = 'Pay',
  'Preserve' = 'Preserve',
  'Regenerate' = 'Regenerate',
  'Save' = 'Save',
  'Send' = 'Send',
  'Secure' = 'Secure',
}
