#!/usr/bin/env bash
# Submits a proposal generated by make-release through Governance.propose() directly.
#
# celocli's governance:propose builds the transactions from its bundled ABIs and fails on
# core contracts it does not know (e.g. BlockchainParametersProxy). This script encodes
# the calls a release proposal contains (XProxy._setImplementation,
# XProxy._setAndInitializeImplementation for a new contract, Registry.setAddressFor) itself. Destinations: Registry/RegistryProxy is the registry
# address; XProxy is the registry address of X, or, when X is registered by this very
# proposal, the address its setAddressFor entry carries.
#
# Usage:
#   scripts/bash/propose-from-json.sh -p <proposal.json> -u <rpc url> -k <proposer key> \
#     -d <description url> [-v <deposit in wei, default: Governance.minDeposit()>]
set -euo pipefail

REGISTRY=0x000000000000000000000000000000000000ce10
PROPOSAL=""
RPC_URL=""
KEY=""
DESCRIPTION_URL=""
DEPOSIT=""

while getopts 'p:u:k:d:v:' flag; do
  case "${flag}" in
    p) PROPOSAL="${OPTARG}" ;;
    u) RPC_URL="${OPTARG}" ;;
    k) KEY="${OPTARG}" ;;
    d) DESCRIPTION_URL="${OPTARG}" ;;
    v) DEPOSIT="${OPTARG}" ;;
    *) echo "Unexpected option ${flag}" >&2; exit 1 ;;
  esac
done
for required in PROPOSAL RPC_URL KEY DESCRIPTION_URL; do
  if [ -z "${!required}" ]; then echo "Missing -$(echo $required | cut -c1 | tr 'PRKD' 'pukd') (${required})" >&2; exit 1; fi
done

registry_address() {
  cast call $REGISTRY "getAddressForString(string)(address)" "$1" --rpc-url "$RPC_URL" | tail -1
}

GOVERNANCE=$(registry_address Governance)
if [ -z "$DEPOSIT" ]; then
  DEPOSIT=$(cast call "$GOVERNANCE" "minDeposit()(uint256)" --rpc-url "$RPC_URL" | tail -1 | cut -d' ' -f1)
fi

COUNT=$(jq 'length' "$PROPOSAL")
VALUES=""
DESTINATIONS=""
LENGTHS=""
DATA="0x"

for i in $(seq 0 $((COUNT - 1))); do
  CONTRACT=$(jq -r ".[$i].contract" "$PROPOSAL")
  FUNCTION=$(jq -r ".[$i].function" "$PROPOSAL")
  VALUE=$(jq -r ".[$i].value" "$PROPOSAL")

  case "$CONTRACT" in
    Registry|RegistryProxy) TARGET=$REGISTRY ;;
    *Proxy)
      BASE=${CONTRACT%Proxy}
      TARGET=$(registry_address "$BASE")
      if [ "$TARGET" = "0x0000000000000000000000000000000000000000" ]; then
        TARGET=$(jq -r --arg b "$BASE" '.[] | select(.function == "setAddressFor" and .args[0] == $b) | .args[1]' "$PROPOSAL" | head -1)
      fi
      ;;
    *) TARGET=$(registry_address "$CONTRACT") ;;
  esac
  if [ -z "$TARGET" ] || [ "$TARGET" = "0x0000000000000000000000000000000000000000" ]; then
    echo "Cannot resolve the destination of entry $i ($CONTRACT.$FUNCTION)" >&2
    exit 1
  fi

  case "$FUNCTION" in
    _setImplementation) CALLDATA=$(cast calldata "_setImplementation(address)" "$(jq -r ".[$i].args[0]" "$PROPOSAL")") ;;
    setAddressFor) CALLDATA=$(cast calldata "setAddressFor(string,address)" "$(jq -r ".[$i].args[0]" "$PROPOSAL")" "$(jq -r ".[$i].args[1]" "$PROPOSAL")") ;;
    _setAndInitializeImplementation) CALLDATA=$(cast calldata "_setAndInitializeImplementation(address,bytes)" "$(jq -r ".[$i].args[0]" "$PROPOSAL")" "$(jq -r ".[$i].args[1]" "$PROPOSAL")") ;;
    *) echo "Entry $i calls $FUNCTION, which this script does not encode" >&2; exit 1 ;;
  esac

  HEX=${CALLDATA#0x}
  DATA="${DATA}${HEX}"
  VALUES="${VALUES}${VALUES:+,}${VALUE}"
  DESTINATIONS="${DESTINATIONS}${DESTINATIONS:+,}${TARGET}"
  LENGTHS="${LENGTHS}${LENGTHS:+,}$(( ${#HEX} / 2 ))"
  echo "[$i] $CONTRACT.$FUNCTION -> $TARGET"
done

echo "Submitting $COUNT transactions to Governance $GOVERNANCE with a deposit of $DEPOSIT wei"
cast send "$GOVERNANCE" "propose(uint256[],address[],bytes,uint256[],string)" \
  "[$VALUES]" "[$DESTINATIONS]" "$DATA" "[$LENGTHS]" "$DESCRIPTION_URL" \
  --value "$DEPOSIT" --private-key "$KEY" --rpc-url "$RPC_URL"
echo "proposalCount is now $(cast call "$GOVERNANCE" 'proposalCount()(uint256)' --rpc-url "$RPC_URL" | tail -1)"
