/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class Attestations extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    attestationRequestFees(arg0: string): TransactionObject<string>

    pendingWithdrawals(arg0: string, arg1: string): TransactionObject<string>

    getAttestationIssuers(
      identifier: string | number[],
      account: string
    ): TransactionObject<(string)[]>

    getAttestationStats(
      identifier: string | number[],
      account: string
    ): TransactionObject<{
      0: string
      1: string
    }>

    batchGetAttestationStats(
      identifiersToLookup: (string | number[])[]
    ): TransactionObject<{
      0: (string)[]
      1: (string)[]
      2: (string)[]
      3: (string)[]
    }>

    getAttestationState(
      identifier: string | number[],
      account: string,
      issuer: string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getAttestationRequestFeeToken(account: string): TransactionObject<string>

    getMostRecentAttestationRequest(account: string): TransactionObject<string>

    getAttestationRequestFee(token: string): TransactionObject<string>

    getDataEncryptionKey(account: string): TransactionObject<(string)[]>

    getWalletAddress(account: string): TransactionObject<string>

    validateAttestationCode(
      identifier: string | number[],
      account: string,
      v: number | string,
      r: string | number[],
      s: string | number[]
    ): TransactionObject<string>

    lookupAccountsForIdentifier(identifier: string | number[]): TransactionObject<(string)[]>

    renounceOwnership(): TransactionObject<void>

    setRegistry(registryAddress: string): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(
      registryAddress: string,
      _attestationExpirySeconds: number | string,
      attestationRequestFeeTokens: (string)[],
      attestationRequestFeeValues: (number | string)[]
    ): TransactionObject<void>

    request(
      identifier: string | number[],
      attestationsRequested: number | string,
      attestationRequestFeeToken: string
    ): TransactionObject<void>

    reveal(
      identifier: string | number[],
      encryptedPhone: (string | number[])[],
      issuer: string,
      sendSms: boolean
    ): TransactionObject<void>

    complete(
      identifier: string | number[],
      v: number | string,
      r: string | number[],
      s: string | number[]
    ): TransactionObject<void>

    revoke(identifier: string | number[], index: number | string): TransactionObject<void>

    withdraw(token: string): TransactionObject<void>

    setAccount(
      dataEncryptionKey: (string | number[])[],
      walletAddress: string
    ): TransactionObject<void>

    setAttestationRequestFee(token: string, fee: number | string): TransactionObject<void>

    setAttestationExpirySeconds(_attestationExpirySeconds: number | string): TransactionObject<void>

    setAccountDataEncryptionKey(dataEncryptionKey: (string | number[])[]): TransactionObject<void>

    setWalletAddress(walletAddress: string): TransactionObject<void>

    initialized(): TransactionObject<boolean>
    registry(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    attestationExpirySeconds(): TransactionObject<string>
    getValidators(): TransactionObject<(string)[]>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    AttestationsRequested(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AttestationCompleted(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    Withdrawal(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AttestationExpirySecondsSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AttestationRequestFeeSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AccountDataEncryptionKeySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    AccountWalletAddressSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    RegistrySet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): Attestations
}
