/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IBondedDeposits extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    isVotingFrozen(arg0: string): TransactionObject<boolean>

    getRewardsLastRedeemed(arg0: string): TransactionObject<string>

    getNoticePeriods(arg0: string): TransactionObject<(string)[]>

    getAvailabilityTimes(arg0: string): TransactionObject<(string)[]>

    getBondedDeposit(
      arg0: string,
      arg1: number | string
    ): TransactionObject<{
      0: string
      1: string
    }>

    getAccountWeight(arg0: string): TransactionObject<string>

    getValidatorFromAccount(arg0: string): TransactionObject<string>

    getAccountFromVoter(arg0: string): TransactionObject<string>

    getAccountFromValidator(arg0: string): TransactionObject<string>

    initialize(arg0: string, arg1: number | string): TransactionObject<void>

    setCumulativeRewardWeight(arg0: number | string): TransactionObject<void>

    setMaxNoticePeriod(arg0: number | string): TransactionObject<void>

    redeemRewards(): TransactionObject<string>

    delegateVoting(
      arg0: string,
      arg1: number | string,
      arg2: string | number[],
      arg3: string | number[]
    ): TransactionObject<void>

    freezeVoting(): TransactionObject<void>

    unfreezeVoting(): TransactionObject<void>

    deposit(arg0: number | string): TransactionObject<string>

    notify(arg0: number | string, arg1: number | string): TransactionObject<string>

    rebond(arg0: number | string, arg1: number | string): TransactionObject<string>

    withdraw(arg0: number | string): TransactionObject<string>

    increaseNoticePeriod(
      arg0: number | string,
      arg1: number | string,
      arg2: number | string
    ): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IBondedDeposits
}
