/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class IExchange extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    getBuyTokenAmount(arg0: number | string, arg1: boolean): TransactionObject<string>

    getSellTokenAmount(arg0: number | string, arg1: boolean): TransactionObject<string>

    getBuyAndSellBuckets(
      arg0: boolean
    ): TransactionObject<{
      0: string
      1: string
    }>

    initialize(
      arg0: string,
      arg1: string,
      arg2: number | string,
      arg3: number | string,
      arg4: number | string,
      arg5: number | string,
      arg6: number | string,
      arg7: number | string
    ): TransactionObject<void>

    exchange(arg0: number | string, arg1: number | string, arg2: boolean): TransactionObject<string>

    setUpdateFrequency(arg0: number | string): TransactionObject<void>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): IExchange
}
