/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class MockBondedDeposits extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    bonded(arg0: string, arg1: number | string): TransactionObject<string>

    voters(arg0: string): TransactionObject<string>

    weights(arg0: string): TransactionObject<string>

    delegations(arg0: string): TransactionObject<string>

    frozen(arg0: string): TransactionObject<boolean>

    validators(arg0: string): TransactionObject<string>

    getAccountWeight(account: string): TransactionObject<string>

    getValidatorFromAccount(account: string): TransactionObject<string>

    getBondedDeposit(
      account: string,
      noticePeriod: number | string
    ): TransactionObject<{
      0: string
      1: string
    }>

    isVotingFrozen(account: string): TransactionObject<boolean>

    getAccountFromVoter(accountOrDelegate: string): TransactionObject<string>

    getAccountFromValidator(accountOrDelegate: string): TransactionObject<string>

    setWeight(account: string, weight: number | string): TransactionObject<void>

    setBondedDeposit(
      account: string,
      noticePeriod: number | string,
      value: number | string
    ): TransactionObject<void>

    setVotingFrozen(account: string): TransactionObject<void>

    delegateVoting(account: string, delegate: string): TransactionObject<void>

    delegateValidating(account: string, delegate: string): TransactionObject<void>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): MockBondedDeposits
}
