
// This file is copied to the abis package for publishing
export const celoRegistryAddress = '0x000000000000000000000000000000000000ce10';

export enum CeloContractName {
  Accounts = 'Accounts',
  Attestations = 'Attestations',
  BlockchainParameters = 'BlockchainParameters',
  CeloToken = 'CeloToken',
  DoubleSigningSlasher = 'DoubleSigningSlasher',
  DowntimeSlasher = 'DowntimeSlasher',
  Election = 'Election',
  EpochRewards = 'EpochRewards',
  EpochManagerEnabler = 'EpochManagerEnabler',
  EpochManager = 'EpochManager',
  ScoreManager = 'ScoreManager',
  Escrow = 'Escrow',
  Exchange = 'Exchange',
  ExchangeEUR = 'ExchangeEUR',
  ExchangeBRL = 'ExchangeBRL',
  FederatedAttestations = 'FederatedAttestations',
  FeeHandler = 'FeeHandler',
  MentoFeeHandlerSeller = 'MentoFeeHandlerSeller',
  FeeCurrencyWhitelist = 'FeeCurrencyWhitelist',
  Freezer = 'Freezer',
  GasPriceMinimum = 'GasPriceMinimum',
  FeeCurrencyDirectory = 'FeeCurrencyDirectory',
  GoldToken = 'GoldToken',
  Governance = 'Governance',
  GovernanceSlasher = 'GovernanceSlasher',
  GovernanceApproverMultiSig = 'GovernanceApproverMultiSig',
  GrandaMento = 'GrandaMento',
  LockedGold = 'LockedGold',
  LockedCelo = 'LockedCelo',
  CeloUnreleasedTreasury = 'CeloUnreleasedTreasury',
  OdisPayments = 'OdisPayments',
  Random = 'Random',
  Reserve = 'Reserve',
  ReserveSpenderMultiSig = 'ReserveSpenderMultiSig',
  SortedOracles = 'SortedOracles',
  StableToken = 'StableToken',
  StableTokenEUR = 'StableTokenEUR',
  StableTokenBRL = 'StableTokenBRL',
  TransferWhitelist = 'TransferWhitelist',
  UniswapFeeHandlerSeller = 'UniswapFeeHandlerSeller',
  Validators = 'Validators'
}
